### ISSUE TITLE
wrong static-ness

### ISSUE THREAD

**Issue by waderwu** [BytecodeDL/soot-fact-generator#7]
```
Fact generation failed for method <org.cyberneko.html.xercesbridge.XercesBridge_2_1: java.lang.String getVersion()>.
soot.ResolutionFailedException: Resolved <org.apache.xerces.impl.Version: java.lang.String getVersion()> to <org.apache.xerces.impl.Version: java.lang.String getVersion()> which has wrong static-ness
	at soot.SootMethodRefImpl.checkStatic(SootMethodRefImpl.java:195)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:212)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:263)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:183)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:56)
	at org.clyze.doop.soot.IrrelevantStmtSwitch.inspectInvoke(IrrelevantStmtSwitch.java:64)
	at org.clyze.doop.soot.IrrelevantStmtSwitch.caseAssignStmt(IrrelevantStmtSwitch.java:24)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:242)
	at org.clyze.doop.soot.FactGenerator.generate(FactGenerator.java:257)
	at org.clyze.doop.soot.FactGenerator.generate(FactGenerator.java:223)
	at org.clyze.doop.soot.FactGenerator.run(FactGenerator.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Error while processing method: <org.cyberneko.html.xercesbridge.XercesBridge_2_1: java.lang.String getVersion()>: Resolved <org.apache.xerces.impl.Version: java.lang.String getVersion()> to <org.apache.xerces.impl.Version: java.lang.String getVersion()> which has wrong static-ness
Fact generation failed (1 errors).
org.clyze.doop.common.DoopErrorCodeException: Doop error #5: Fact generation failed (1 errors).
	at org.clyze.doop.common.DoopErrorCodeException.error5(DoopErrorCodeException.java:33)
	at org.clyze.doop.common.Driver.shutdownExecutor(Driver.java:83)
	at org.clyze.doop.common.Driver.doInParallel(Driver.java:62)
	at org.clyze.doop.common.Driver.generateInParallel(Driver.java:89)
	at org.clyze.doop.soot.Main.invokeSoot(Main.java:296)
	at org.clyze.doop.soot.Main.lambda$produceFacts$1(Main.java:127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Fact generation failed (1 errors).
	at org.clyze.doop.common.DoopErrorCodeException.<init>(DoopErrorCodeException.java:162)
	... 9 more
Exception in thread "main" org.clyze.doop.common.DoopErrorCodeException: Doop error #34: Fact generation failed with 1 errors.
	at org.clyze.doop.common.DoopErrorCodeException.error34(DoopErrorCodeException.java:149)
	at org.clyze.doop.soot.Main.produceFacts(Main.java:138)
	at org.clyze.doop.soot.Main.main(Main.java:44)
Caused by: java.lang.RuntimeException: Fact generation failed with 1 errors.
	at org.clyze.doop.common.DoopErrorCodeException.<init>(DoopErrorCodeException.java:162)
	... 3 more
```

**Comment by SuperXiaoxiong** [comment]
有解决办法么

**Comment by waderwu** [comment]
这个加个参数就行了，`--ignore-wrong-staticness`
